### ISSUE TITLE
BUG: (BoxPath) space is also an effective path

### ISSUE THREAD

**Issue by wyhaya** [bbqsrc/box#4]
```rust
use box_format::BoxPath;
fn main() {
    let p = BoxPath::new("./a/ /b").unwrap(); 
    // Error: UnrepresentableStr
}
```

On `Windows` `Linux` `macOS`,  space('  ') is also a valid path

**Comment by bbqsrc** [comment]
On Linux and macOS, a newline is also a valid path. Box paths are highly opinionated paths that try to avoid any input that leads to confusion, and that means if trimming it leads to a different shape, it isn't allowed. " foo ", " foo", "foo " and " " are all invalid paths.

**Comment by wyhaya** [comment]
Thank you for the explanation.
